# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? 4. ??? 12:08:20 2010
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile
#  Description : Wrapper Makefile for calling Symbian build tools
#
# ==============================================================================


MAKEFILE          = Makefile
QMAKE             = c:\qt\4.6.2-symbian\bin\qmake.exe
DEL_FILE          = del
DEL_DIR           = rmdir
MOVE              = move
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\Z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/Qt/4.6.2-symbian/include/QtCore" -I"C:/Qt/4.6.2-symbian/include/QtCore/tmp" -I"C:/Qt/4.6.2-symbian/include/QtGui" -I"C:/Qt/4.6.2-symbian/include/QtGui/tmp" -I"C:/Qt/4.6.2-symbian/include/phonon" -I"C:/Qt/4.6.2-symbian/include/phonon/tmp" -I"C:/Qt/4.6.2-symbian/include" -I"C:/Qt/4.6.2-symbian/include/tmp" -I"C:/Qt/4.6.2-symbian/mkspecs/common/symbian" -I"C:/Qt/4.6.2-symbian/mkspecs/common/symbian/tmp" -I"C:/S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/include" -I"C:/Users/mir/Documents/hj" -I"C:/Users/mir/Documents/hj/tmp" -I"C:/S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/include/stdapis" -I"C:/S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/include/stdapis/sys" -I"C:/S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/include/stdapis/stlport" -I"C:/Qt/4.6.2-symbian/include/phonon_compat" -I"C:/Qt/4.6.2-symbian/include/phonon_compat/tmp" -I"C:/S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/include/domain/middleware" -I"C:/S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/include/domain/middleware/loc"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) -spec symbian-abld -o "bld.inf" "C:/Users/mir/Documents/hj/hj.pro"

bld.inf:
	$(QMAKE)

$(ABLD): bld.inf
	bldmake bldfiles

debug: $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: $(ABLD)
	$(ABLD) build gcce urel
release-armv5: $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

C:\Qt\4.6.2-symbian\bin\moc.exe:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_modelt.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_modelt.cpp 2> NUL
moc_mainwindow.cpp: modelt.h \
		info.h \
		mainwindow.h \
		..\..\..\..\Qt\4.6.2-symbian\bin\moc.exe
	C:\Qt\4.6.2-symbian\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN mainwindow.h -o moc_mainwindow.cpp

moc_modelt.cpp: info.h \
		modelt.h \
		..\..\..\..\Qt\4.6.2-symbian\bin\moc.exe
	C:\Qt\4.6.2-symbian\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN modelt.h -o moc_modelt.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp 2> NUL
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h 2> NUL
ui_mainwindow.h: mainwindow.ui
	c:\Qt\4.6.2-symbian\bin\uic.exe mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

create_temps:
	-@ if NOT EXIST "C:\Qt\4.6.2-symbian\include\QtCore\tmp" mkdir "C:\Qt\4.6.2-symbian\include\QtCore\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.2-symbian\include\QtGui\tmp" mkdir "C:\Qt\4.6.2-symbian\include\QtGui\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.2-symbian\include\phonon\tmp" mkdir "C:\Qt\4.6.2-symbian\include\phonon\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.2-symbian\include\tmp" mkdir "C:\Qt\4.6.2-symbian\include\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.2-symbian\mkspecs\common\symbian\tmp" mkdir "C:\Qt\4.6.2-symbian\mkspecs\common\symbian\tmp"
	-@ if NOT EXIST "C:\Users\mir\Documents\hj\tmp" mkdir "C:\Users\mir\Documents\hj\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.2-symbian\include\phonon_compat\tmp" mkdir "C:\Qt\4.6.2-symbian\include\phonon_compat\tmp"

extension_clean: compiler_clean
	-@ if EXIST "C:\Qt\4.6.2-symbian\include\QtCore\tmp" rmdir  /S /Q  "C:\Qt\4.6.2-symbian\include\QtCore\tmp"
	-@ if EXIST "C:\Qt\4.6.2-symbian\include\QtGui\tmp" rmdir  /S /Q  "C:\Qt\4.6.2-symbian\include\QtGui\tmp"
	-@ if EXIST "C:\Qt\4.6.2-symbian\include\phonon\tmp" rmdir  /S /Q  "C:\Qt\4.6.2-symbian\include\phonon\tmp"
	-@ if EXIST "C:\Qt\4.6.2-symbian\include\tmp" rmdir  /S /Q  "C:\Qt\4.6.2-symbian\include\tmp"
	-@ if EXIST "C:\Qt\4.6.2-symbian\mkspecs\common\symbian\tmp" rmdir  /S /Q  "C:\Qt\4.6.2-symbian\mkspecs\common\symbian\tmp"
	-@ if EXIST "C:\Users\mir\Documents\hj\tmp" rmdir  /S /Q  "C:\Users\mir\Documents\hj\tmp"
	-@ if EXIST "C:\Qt\4.6.2-symbian\include\phonon_compat\tmp" rmdir  /S /Q  "C:\Qt\4.6.2-symbian\include\phonon_compat\tmp"

pre_targetdeps: \
	generated_sources \
	all_source_deps \
	ui_mainwindow.h

generated_sources: \
	moc_mainwindow.cpp \
	moc_modelt.cpp

all_source_deps: \
	mainwindow.h \
	modelt.h \
	info.h \
	ui_mainwindow.h

finalize:

winscw_deployment:

winscw_deployment_clean:

-include .make.cache

sis:
	$(if $(wildcard hj_template.pkg),$(if $(wildcard .make.cache),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(if $(QT_SIS_TARGET),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nocache)),$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_sis:
	createpackage.bat $(QT_SIS_OPTIONS) hj_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

hj.sis:
	$(MAKE) -s -f $(MAKEFILE) sis

installer_sis: hj.sis
	$(if $(wildcard hj_installer.pkg),$(MAKE) -s -f $(MAKEFILE) ok_installer_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_installer_sis: 
	createpackage.bat $(QT_SIS_OPTIONS) hj_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

fail_sis_nopkg:
	$(error PKG file does not exist, 'sis' and 'installer_sis' target are only supported for executables or projects with DEPLOYMENT statement)

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

store_build:
	@echo # ============================================================================== > .make.cache
	@echo # This file is generated by make and should not be modified by the user >> .make.cache
	@echo #  Name        : .make.cache >> .make.cache
	@echo #  Part of     : hj >> .make.cache
	@echo #  Description : This file is used to cache last build target for >> .make.cache
	@echo #                make sis target. >> .make.cache
	@echo #  Version     :  >> .make.cache
	@echo # >> .make.cache
	@echo # ============================================================================== >> .make.cache
	@echo. >> .make.cache
	@echo QT_SIS_TARGET ?= $(QT_SIS_TARGET) >> .make.cache

dodistclean:
	-@ if EXIST "c:\Users\mir\Documents\hj\hj_template.pkg" $(DEL_FILE)  "c:\Users\mir\Documents\hj\hj_template.pkg"
	-@ if EXIST "c:\Users\mir\Documents\hj\hj_installer.pkg" $(DEL_FILE)  "c:\Users\mir\Documents\hj\hj_installer.pkg"
	-@ if EXIST "c:\Users\mir\Documents\hj\Makefile" $(DEL_FILE)  "c:\Users\mir\Documents\hj\Makefile"
	-@ if EXIST "c:\Users\mir\Documents\hj\Makefile_0xEfec926d.mk" $(DEL_FILE)  "c:\Users\mir\Documents\hj\Makefile_0xEfec926d.mk"
	-@ if EXIST "c:\Users\mir\Documents\hj\hj_0xEfec926d.mmp" $(DEL_FILE)  "c:\Users\mir\Documents\hj\hj_0xEfec926d.mmp"
	-@ if EXIST "c:\Users\mir\Documents\hj\hj_reg.rss" $(DEL_FILE)  "c:\Users\mir\Documents\hj\hj_reg.rss"
	-@ if EXIST "c:\Users\mir\Documents\hj\hj.rss" $(DEL_FILE)  "c:\Users\mir\Documents\hj\hj.rss"
	-@ if EXIST "c:\Users\mir\Documents\hj\hj.loc" $(DEL_FILE)  "c:\Users\mir\Documents\hj\hj.loc"
	-@ if EXIST "c:\Users\mir\Documents\hj\.make.cache" $(DEL_FILE)  "c:\Users\mir\Documents\hj\.make.cache"
	-@ if EXIST "c:\Users\mir\Documents\hj\bld.inf" $(DEL_FILE)  "c:\Users\mir\Documents\hj\bld.inf"

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

clean-debug: $(ABLD)
	$(ABLD) reallyclean winscw udeb
	$(ABLD) reallyclean gcce udeb
	$(ABLD) reallyclean armv5 udeb
	$(ABLD) reallyclean armv6 udeb

clean-release: $(ABLD)
	$(ABLD) reallyclean gcce urel
	$(ABLD) reallyclean armv5 urel
	$(ABLD) reallyclean armv6 urel

clean-debug-winscw: $(ABLD)
	$(ABLD) reallyclean winscw udeb
clean-debug-gcce: $(ABLD)
	$(ABLD) reallyclean gcce udeb
clean-debug-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 udeb
clean-debug-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 udeb
clean-release-gcce: $(ABLD)
	$(ABLD) reallyclean gcce urel
clean-release-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 urel
clean-release-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 urel

run:
	-call /S60/devices/Nokia_N97_SDK_v1.0_2/epoc32/release/winscw/udeb/hj.exe $(QT_RUN_OPTIONS)
runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis hj_$(QT_SIS_TARGET).sis hj.exe $(QT_RUN_OPTIONS)

